
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: tenantdb
      POSTGRES_USER: tenantadmin
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

volumes:
  pgdata:
